# Generated by Django 3.2.8 on 2021-10-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='episode_slug',
            new_name='slug',
        ),
    ]
