# Generated by Django 3.2.8 on 2021-10-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_rename_episode_slug_episode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
