# Generated by Django 3.2.8 on 2021-10-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0003_alter_episode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
