# Generated by Django 3.2.8 on 2021-10-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_remove_show_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, upload_to='show_images'),
        ),
    ]
