# Generated by Django 3.2.8 on 2021-10-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_show_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
